### ISSUE TITLE
initialize should be defined on each struct class returned by new, not on KwStruct

### ISSUE THREAD

**Issue by bughit** [maxim/kwstruct#1]
Also Struct needlessly overloads new to mean "create a subclass" why repeat that mistake, we have enough words.

``` ruby
class KwStruct < Struct
  private_class_method :new
  def self.define(*members, &block)
    new(*members, &block).tap do |struct_class|
      struct_class.send :define_method, :initialize do |**values_map|
        unless (unknown_members = values_map.keys - members).empty?
          raise ArgumentError.new("Unknown member(s): #{unknown_members.join(', ')}")
        end
        super(*members.map{|member| values_map[member]})
      end
    end
  end
end
```

**Comment by maxim** [comment]
Thank you @bughit, that's pretty critical. I added the `tap`, and with some effort managed to come up with the test that verifies this issue. Imo it's better to use ruby's native keyword args rather than reimplement the option checks, so I didn't take that part. Also decided not to use `define` for now, (even though I agree it's a better word) since the goal here is to minimally extend Struct with kwargs support, not write better Struct. Gotta stay consistent in all other ways.
